http:
  routers:
    traefik:
      tls:
        domains:
        - main: "docker.localhost"
          sans:
            - "*.docker.localhost"
        - main: "domain.local"
          sans:
            - "*.domain.local"
tls:
  certificates:
  - certFile: "/etc/certs/local-cert.pem"
    keyFile: "/etc/certs/local-key.pem"