global:
  sendAnonymousUsage: false
ping:
  entryPoint: http
api:
  dashboard: true
  insecure: true
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true
  consulCatalog:
    defaultRule: "Host(`{{ .Name }}.docker.localhost`)"
    endpoint:
      address: 127.0.0.1:8500
      datacenter: europe-paris
    exposedbydefault: false
log:
  level: INFO
  format: json
entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'
