version: '3'

services:

  consul-server-1:
    image: 'hashistack-alpine:1.0.0'
    container_name: consul-server-1
    restart: 'unless-stopped'
    volumes:
    - './configs/consul-server.hcl:/home/root/consul.hcl:ro'
    networks:
    - 'public-subnet'
    - 'private-subnet'
    command: ['consul', 'agent', '-config-file=/home/root/consul.hcl']

  consul-server-2:
    image: 'hashistack-alpine:1.0.0'
    container_name: consul-server-2
    restart: 'unless-stopped'
    volumes:
    - './configs/consul-server.hcl:/home/root/consul.hcl:ro'
    networks:
    - 'public-subnet'
    - 'private-subnet'
    command: ['consul', 'agent', '-config-file=/home/root/consul.hcl']

  consul-server-3:
    image: 'hashistack-alpine:1.0.0'
    container_name: consul-server-3
    restart: 'unless-stopped'
    volumes:
    - './configs/consul-server.hcl:/home/root/consul.hcl:ro'
    networks:
    - 'public-subnet'
    - 'private-subnet'
    command: ['consul', 'agent', '-config-file=/home/root/consul.hcl']

networks:

  public-subnet:
    external: true

  private-subnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.0.20.0/24
          gateway: 174.0.20.1