# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
    end
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.1.16"

    config.vm.define "ubuntu20.04" do |ubuntu|
        ubuntu.vm.hostname = "ubuntu20.04"
    end

    config.vm.network "public_network", bridge: "public-subnet"

    config.vm.provision "file", source: "../certs/consul-agent-ca.pem", destination: "/home/vagrant/certs/consul-agent-ca.pem"
    config.vm.provision "file", source: "./consul.hcl", destination: "/home/vagrant/consul.hcl"
    config.vm.provision "file", source: "./nomad.hcl", destination: "/home/vagrant/nomad.hcl"
    config.vm.provision:shell, path: "setup.sh"
end