version: '3'

services:

  traefik:
    image: 'traefik:v2.4.7'
    container_name: 'traefik'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.traefik=true'
    - 'traefik.http.routers.traefik.tls=true'
    - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
    ports:
    - '80:80/tcp'
    - '443:443/tcp'
    restart: 'unless-stopped'
    security_opt:
    - 'no-new-privileges:true'
    networks:
    - 'public-subnet'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - './configs/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro'
    - './configs/traefik.yaml:/etc/traefik/traefik.yaml:ro'
    - '../certs:/etc/certs:ro'

  consul-client-traefik:
    image: 'hashistack-alpine:1.0.0'
    container_name: 'consul-client-traefik'
    restart: 'unless-stopped'
    volumes:
    - '../consul/configs/client.hcl:/home/root/consul.hcl:ro'
    networks:
    - 'public-subnet'
    command: ['consul', 'agent', '-config-file=/home/root/consul.hcl', '-node=node-traefik']

networks:

  public-subnet:
    external: true
  
  # private-subnet:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 174.0.10.0/24
  #         gateway: 174.0.10.1