version: '3'

services:

  traefik:
    image: 'traefik:v2.4.7'
    container_name: 'traefik'
    network_mode: 'host'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.traefik=true'
    - 'traefik.http.routers.traefik.tls=true'
    - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
    restart: 'unless-stopped'
    security_opt:
    - 'no-new-privileges:true'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - './traefik/configs/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro'
    - './traefik/configs/traefik.yaml:/etc/traefik/traefik.yaml:ro'
    - './certs:/etc/certs:ro'

  consul-client:
    image: 'hashistack-alpine:1.0.0'
    container_name: 'consul-client-traefik'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
    - './consul/configs/client.hcl:/home/root/consul.hcl:ro'
    - './certs/consul-agent-ca.pem:/home/root/certs/consul-agent-ca.pem:ro'
    command:
    - '/root/bin/consul'
    - 'agent'
    - '-config-file=/home/root/consul.hcl'
    - '-node=node-localhost'
    - '-advertise=192.168.50.1'

