# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
CONSUL_VERSION = "1.11.1"
NOMAD_VERSION = "1.2.3"
INSTANCES_COUNT = 1

def assignIP(num)
    return "192.168.50.#{num+10}"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.1.16"
    (1..INSTANCES_COUNT).each do |i|
        config.vm.define vm_instance_name = "nomad-client-%d" % i do |instance|
            instance.vm.hostname = vm_instance_name
            instance.vm.network "private_network", ip: assignIP(i)

            # install files
            instance.vm.provision "file", source: "../certs", destination: "/home/vagrant/certs"
            instance.vm.provision "file", source: "../consul/configs/client.hcl", destination: "/home/vagrant/consul.hcl"
            instance.vm.provision "file", source: "../nomad/configs/client.hcl", destination: "/home/vagrant/nomad.hcl"

            # install tools
            instance.vm.provision :shell,
            inline: <<-EOF
                echo "[INFO] install tools"
                sudo apt update
                sudo apt install -y net-tools curl
                echo "[INFO] install hashi-up"
                curl -sLS https://get.hashi-up.dev | sh
                hashi-up version
                echo "[INFO] install consul"
                hashi-up consul install --local --version #{CONSUL_VERSION} --config-file /home/vagrant/consul.hcl
                echo "[INFO] install nomad"
                hashi-up nomad install --local --version #{NOMAD_VERSION} --config-file /home/vagrant/nomad.hcl
            EOF

            # install docker
            instance.vm.provision :docker
        end
    end
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 3072
    end
end