global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedbydefault: false
  consulCatalog:
    endpoint:
      address: consul-client-traefik:8500
      datacenter: europe-paris
    exposedbydefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

log:
  level: INFO
  format: json

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
