global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  # consulCatalog:
  #   endpoint:
  #     address: consul-server-1:8500
  #     datacenter: global
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'